In [1]:
#1
# Import the numpy package under the name np
import numpy as np

In [2]:
#2
#Print the numpy version and the configuration
print(np.__version__)
np.show_config()

2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-p45mh2dm/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Program Files\Python311\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [5]:
#3
#Create a null vector of size 10
vector=np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
#4
#How to find the memory size of any array
array=np.zeros((10,10))
print('Memory Size of array is', array.itemsize*array.size)

Memory Size of array is 800


In [ ]:
#5
# How to get the documentation of the numpy add function from the command line?
%run `python -c "import numpy; numpy.info(numpy.add)"`

In [10]:
#6
#Create a null vector of size 10 but the fifth value which is 1 
vector2=np.zeros(10)
vector2[4]=1
print(vector2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
#7
#Create a vector with values ranging from 10 to 49
vector3=np.arange(10,50)
print(vector3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#8
#Reverse a vector (first element becomes last) 
vector4=np.arange(20)
vector4=vector4[::-1]
print(vector4)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [13]:
#9
#Create a 3x3 matrix with values ranging from 0 to 8 
matrix=np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#10
#Find indices of non-zero elements from [1,2,0,0,4,0] 
non_zero=np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


In [15]:
#11
#Create a 3x3 identity matrix
matrix2=np.eye(3)
print(matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#12
#Create a 3x3x3 array with random values
matrix3=np.random.random((3,3,3))
print(matrix3)

[[[0.09003028 0.59776033 0.33229172]
  [0.31323541 0.95961751 0.03805267]
  [0.75352979 0.08191908 0.10208593]]

 [[0.72416119 0.30810264 0.48830732]
  [0.0919511  0.45251886 0.71992656]
  [0.85166029 0.90604189 0.26002854]]

 [[0.68283677 0.93819348 0.31146988]
  [0.17988193 0.84701779 0.75405911]
  [0.62931658 0.50521596 0.74296757]]]


In [17]:
#13
#Create a 10x10 array with random values and find the minimum and maximum values
matrix4=np.random.random((10,10))
m4Min=matrix4.min()
m4Max=matrix4.max()
print(m4Min,m4Max)

0.004996255701185115 0.9860274670688877


In [18]:
#14
#Create a random vector of size 30 and find the mean value
vector5=np.random.random(30)
meanV=vector5.mean()
print(meanV)

0.5359495251817256


In [23]:
#15
#Create a 2d array with 1 on the border and 0 inside
array2=np.ones((7,7))
array2[1:-1,1:-1]=0
print(array2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [29]:
#16
#How to add a border (filled with 0's) around an existing array?
array3=np.ones((8,8))
array3=np.pad(array3,pad_width=1,mode='constant', constant_values=0)
print(array3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [30]:
#17
#What is the result of the following expression? 
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [35]:
#18
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix5=np.diag(1+np.arange(4), k=-1)
print(matrix5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [37]:
#19
# Create a 8x8 matrix and fill it with a checkerboard pattern 
matrix6=np.zeros((8,8), dtype=int)
matrix6[1::2,::2]=1
matrix6[::2, 1::2]=1
print(matrix6)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [38]:
#20
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


In [39]:
#21
#Create a checkerboard 8x8 matrix using the tile function
matrix7=np.tile(np.array([[0,1],[1,0]]), (4,4))
print(matrix7)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
#22
#Normalize a 5x5 random matrix
matrix8=np.random.random((5,5))
matrix8=(matrix8-np.mean(matrix8)/np.std(matrix8))
print(matrix8)

[[-1.16377721 -0.7837008  -0.71522517 -0.95233633 -0.63889807]
 [-1.51016246 -0.63610581 -1.32460718 -0.55880048 -1.15368645]
 [-0.84751146 -0.54329259 -1.15969636 -1.29939222 -1.23379769]
 [-1.50418348 -0.65563687 -0.54593578 -1.51026433 -1.3939037 ]
 [-1.33267675 -0.58617343 -0.76000998 -1.34800807 -0.80127702]]


In [44]:
#23
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b", np.ubyte,1),("a",np.ubyte,1)])

In [45]:
#24
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix9=np.dot(np.ones((5,3)),np.ones((3,2)))
print(matrix9)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [48]:
#25
#Given a 1D array, negate all elements which are between 3 and 8, in place.
array4=np.arange(20)
array4[(3<=array4)&(array4<=8)]*=-1
print(array4)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
#26
#What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [54]:
#27
#Consider an integer vector Z, which of these expressions are legal?
array4**array4 
2 << array4 >> 2
array4 <- array4
1j*array4
array4/1/1
array4<array4>array4

ValueError: Integers to negative integer powers are not allowed.

In [55]:
#28
#What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\nizom\AppData\Local\Temp\ipykernel_4788\3494967180.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\nizom\AppData\Local\Temp\ipykernel_4788\3494967180.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\nizom\AppData\Local\Temp\ipykernel_4788\3494967180.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [56]:
#29
# How to round away from zero a float array ?
array=np.random.uniform(-6,+6,6)
print(np.copysign(np.ceil(np.abs(array)),array))

[ 5.  2. -3.  6. -1.  2.]


In [58]:
#30
arr1=np.random.randint(0,10,10)
arr2=np.random.randint(0,7,7)
print(np.intersect1d(arr1,arr2))

[0 1 2 3 6]
